credentials:
  usernames:
    skarlekar:
      email: skarlekar@gmail.com
      name: Srini Karlekar
      password: $2b$12$7sI61ohMYYxgST/RncsQveNZof7qkS0X4JM8BmTSqjk21UgfC/4Ue
    psoundappan:
      email: psoundappan@gmail.com
      name: Prabhu Soundappan
      password: $2b$12$8BL3koB3FeK8qbD6ibKtuernsEkMUS0HkL65zCjB2tyivUG7AWgam # To be replaced with hashed password
    sfischer:
      email: Sjfischr@gmail.com
      name: Steve Fischer
      password: $2b$12$GZbdFTXg7o9uwh0/aK.NW.deYVthuTBzGrCJGIQv7GTP6BeO/gbFq
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: ssk_streamlit
preauthorized:
  emails:
  - skarlekar@gmail.com
  - psoundappan@gmail.com
  - Sjfischr@gmail.com

